# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Towards Open-World Object-based Anomaly Detection via Self-Supervised Outlier Synthesis"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Accepted at ECCV 2024
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
authors:
  - link: https://kostadinovshalon.github.io
    name: Brian K. S. Isaac-Medina
    institution: Durham University
  - link: https://yonafalinie.github.io/
    name: Yona Falinie Abd. Gaus
    institution: Durham University
  - link: https://www.durham.ac.uk/staff/neelanjan-bhowmik/
    name: Neelanjan Bhowmik
    institution: Durham University
  - link: https://breckon.org/breckon
    name: Toby Breckon
    institution: Durham University
links:
  - img: images/paper-icon.png
    link: https://arxiv.org/abs/2407.15763
    title: Paper
  - img: images/github-icon.png
    link: https://github.com/KostadinovShalon/oln-ssos
    title: Code
#  - img: images/yt.ico
#    link: https://youtu.be/1ck25jJdw7A
#    title: Video
# Build settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-remote-theme
theme: jekyll-theme-cayman

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
